services:
  frontend:
    build: ./frontend
    command: npm run dev -- --host 0.0.0.0
    # env_file:
    #   - fileName
    ports:
      - 5173:5173
    volumes:
      - ./frontend/public/:/app/public/:rw
      - ./frontend/src/:/app/src/:rw
      - ./frontend/package.json:/app/package.json

  backend:
    build: ./backend
    command: ["mvn", "spring-boot:run"]
    ports:
      - 8080:8080
    volumes:
      - ./backend/src/:/app/src/:rw
      - ./backend/pom.xml:/app/pom.xml
