services:
  frontend:
    build: ./frontend
    # env_file:
    #   - fileName
    ports:
      - 5173:5173
    volumes:
      - ./frontend/public/:/app/public/:rw
      - ./frontend/src/:/app/src/:rw
      - ./frontend/package.json:/app/package.json

  backend:
    build: ./backend
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      HOME: /root
      DB_NAME: ${DB_NAME:-digicheese}
      DB_USER: ${DB_USER:-digicheese}
      DB_PASSWORD: ${DB_PASSWORD:-digicheese}  
    volumes:
      - ./backend/src/:/app/src/:rw
      - ./backend/pom.xml:/app/pom.xml
      - maven_cache:/root/.m2
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-digicheese}
      POSTGRES_USER: ${DB_USER:-digicheese}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-digicheese}
      PGDATA: /var/lib/postgresql/data/customDataFolder
    volumes:
      - ./dbData/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${DB_NAME:-digicheese} -U ${DB_USER:-digicheese}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  maven_cache: